from .models import Base, Mention, IntentTag, Reply, Keyword, AlertConfig
from .crud import (
    init_db,
    get_session,
    upsert_mention,
    get_mention_by_id,
    update_mention_analysis,
    get_unprocessed_mentions,
    get_all_mentions_for_reclassify,
    get_mentions_filtered,
    get_mentions_by_keyword,
    get_recent_mentions,
    delete_mention,
    get_dashboard_stats,
    add_intent_tag,
    get_intent_tags,
    add_reply,
    update_reply_content,
    get_unsent_replies,
    mark_reply_sent,
    add_keyword,
    get_all_keywords,
    get_active_keywords,
    update_keyword_active,
    delete_keyword,
    delete_keyword_by_id,
    get_alert_config,
    upsert_alert_config,
)

from .vector_search import semantic_search, keyword_search, embed_text

__all__ = [
    "Base",
    "Mention",
    "IntentTag",
    "Reply",
    "Keyword",
    "AlertConfig",
    "init_db",
    "get_session",
    "upsert_mention",
    "get_mention_by_id",
    "get_unprocessed_mentions",
    "get_mentions_filtered",
    "get_mentions_by_keyword",
    "get_recent_mentions",
    "delete_mention",
    "get_dashboard_stats",
    "add_intent_tag",
    "get_intent_tags",
    "add_reply",
    "update_reply_content",
    "get_unsent_replies",
    "mark_reply_sent",
    "add_keyword",
    "get_all_keywords",
    "get_active_keywords",
    "update_keyword_active",
    "delete_keyword",
    "delete_keyword_by_id",
    "get_alert_config",
    "upsert_alert_config",
    "semantic_search",
    "keyword_search",
    "embed_text",
]